### PR TITLE
add div to solve #745

### PR DESCRIPTION
**Pull request by GVogeler**

### CODE REVIEW

**Comment by GVogeler** [comment]
check if  `id="witList"` in line 145 can be deleted as well

**Comment by StephanMa** [comment]
In this PR, you have just removed the ID... 
how are you toggling the hidding with javascript without id?#
Or did i miss something?

@yngwi what do you think?

**Comment by yngwi** [comment]
> In this PR, you have just removed the ID...
> how are you toggling the hidding with javascript without id?#
> Or did i miss something?
> 
> @yngwi what do you think?

Looks OK to me

**Comment by GVogeler** [comment]
https://github.com/icaruseu/mom-ca/pull/996#issuecomment-767412647: 

> In this PR, you have just removed the ID...
> how are you toggling the hidding with javascript without id?#
> Or did i miss something?

and adding an `@id`: 
https://github.com/icaruseu/mom-ca/pull/996/files#diff-4a564f8bae64ac5bd66d1c1ba18f1d97b417fcfab0adec88b6ef2ad6a6aa0463R141

**Pull request merged**
