### PR TITLE
change cei:witListPar handling to solve #535

### PR DESCRIPTION
**Pull request by GVogeler**

### CODE REVIEW

**Comment by icarus-eu** [comment]
This fix doesn't change anything for me when i tried it on the dev server.

Live server:
live

Dev server:
dev

**Comment by GVogeler** [comment]
Hmm, too bad. Example contains:
```
<cei:witnessOrig>
                        <cei:figure>
                            <cei:graphic url="Goettingen_App_Dipl_397_15850905_r.JPG"/>
                        </cei:figure>
                        <cei:figure>
                            <cei:graphic url="Goettingen_App_Dipl_397_15850905_v.JPG"/>
                        </cei:figure>
                        <cei:archIdentifier>
                            <cei:arch>Göttingen, Diplomatischer Apparat</cei:arch>
                            <cei:archFond>App. dipl.</cei:archFond>
                            <cei:idno>397</cei:idno>
                        </cei:archIdentifier>
                        <cei:traditioForm>ins.</cei:traditioForm>
                    </cei:witnessOrig>
                    <cei:witListPar>
                        <cei:witness>
                            <cei:traditioForm>cop. </cei:traditioForm>App. dipl. 51</cei:witness>
                    </cei:witListPar>
```
thus there should be two entries.

**Comment by icarus-eu** [comment]
Yes, I'm aware of that. It seems as if the fix doesn't work. Here is a screen-shot of the full page. Am I looking at the wrong place?
capture

**Comment by GVogeler** [comment]
Yes, I don't know why I every assumed that the previous commit should fix issue #535 . The commit https://github.com/icaruseu/mom-ca/pull/702/commits/87795a870c24f5be67afd570f0031919ee797f01 should do the trick, at least in my local machine.

**Pull request merged**
