### PR TITLE
Update cei.xsd

### PR DESCRIPTION
**Pull request by StephanMa**
add maxoccurs to cei:Abstracts

---
This change is [Reviewable](https://reviewable.io/reviews/icaruseu/mom-ca/968)

### CODE REVIEW

**Comment by GVogeler** [comment]
attention: every change in cei.xsd has to be replicated in cei10.xsd (which is a XSD 1.0 version of cei.xsd), see #205

**Comment by StephanMa** [comment]
@GVogeler cei10.xsd is not referenced once.. Seems it isnt used any more.
But if you want to, i will add cei10.xsd to this pr

**Comment by GVogeler** [comment]
If it's not used anymore we can delete it and close #205 .

**Review by yngwi — APPROVED** [review]
lgtm 👌

**Pull request merged**
