### PR TITLE
TwitterTimeline

### PR DESCRIPTION
**Pull request by JBigalke**
Added new Package /mom/app.external with the files
  external.app.xml
  twitter.js

Added function to create a Twitter-Time of "@monasterium.net" on the Mom-ca Start-Page.

---
This change is [Reviewable](https://reviewable.io/reviews/icaruseu/mom-ca/512)

### CODE REVIEW

**Comment by icarus-eu** [comment]
@jbigalke Is the commit meant to completely implement the twitter timeline? The pull request adds an empty box to the mom-ca landing page (see below) but doesn't add any content.

---------------



---







*Comments from [Reviewable](https://reviewable.io:443/reviews/icaruseu/mom-ca/512#-:-KXuAbvfPvKp2qrt_iwJ:b-v7wmch)*

**Comment by icarus-eu** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/icaruseu/mom-ca/512)*

**Comment by JBigalke** [comment]
Hmm, there is a new app with the name external.app, but it seems that i did something wrong with the commit.

**Comment by icarus-eu** [comment]
ah ok

**Comment by JBigalke** [comment]
Now there should be 3 files changed
Two new Files: 
   external.app
   twitter.js

and the changed file:  home.widget.xml

**Comment by icarus-eu** [comment]
Thanks for the changes. It works now although I have the feeling we will have to place it somewhere else. @GVogeler @StephanMa @maburg what do you think?

---

capture

**Comment by GVogeler** [comment]
What about moving the "currently online"/"new fonds" widget to the left side and use the left only?

**Comment by yngwi** [comment]
The problem is that the Layout width seems to be fixed. Having another widget would leave very little space for the main text. I don't have a better idea yet, though...

**Comment by GVogeler** [comment]
Alternative place would be below the introductory text, thus for example:
Home
[ Introductory text ] [ numbers ]
[ XXX (e.g. news) ] [ tweets ] [new fonds ]

Or change the [new fonds]-widget into something horizontal fitting better below the introductiorary text.
I would suggest to postpone this question to refactoring of the layout (e.g. #186 ) and use the three column solution for now.

**Comment by GVogeler** [comment]
legacy ...

**Pull request closed without merging**
