### PR TITLE
GeoServices for Archvies

### PR DESCRIPTION
**Pull request by JBigalke**
- Added new lib leaflet to Monasterium to show Maps in Monasterium.net
- Added new app GeoServices. 
- Added in mom/fonds.widget.xml funktion to show a map with Geoinformations about the Archives.

### CODE REVIEW

**Comment by yngwi** [comment]
I like the change in general. However, there are two things that bother me: 

1. The map is not zoomed out to show all archives when initially loading the page. I think it would be better if the zoom would be automatically adjusted to display everything to not give an archive the feeling that they are not worth putting in the spotlight. What do you think?

2. The CSS is slightly off for the alignment of the new expand/collapse bars and the fond list below: 
capture

**Comment by GVogeler** [comment]
on question 1: Is https://leafletjs.com/reference-1.3.4.html#map-fitbounds might be the solution?

**Comment by icarus-eu** [comment]
Maybe just zoom out so all of Europe is shown. We will (for instance) get ~10000 Finnish charters so Northern Europe will be much more important anyways...

**Comment by icarus-eu** [comment]
capture

**Comment by JBigalke** [comment]
grafik


with .setView in Map.constructor = ([ 51.50, 20.21 ], 4)

**Pull request merged**
