### PR TITLE
enhancements for single charter view (+ minor changes in build file)

### PR DESCRIPTION
**Pull request by digsc**
latest version of digsc:master is running on http://dev.monasterium.net

### CODE REVIEW

**Comment by GVogeler** [comment]
https://github.com/digsc/mom-ca/commit/84a27ac911604c150328687c90ecc7383caaffe5 and https://github.com/digsc/mom-ca/commit/d0ea09f2daf9e0b45faae1f7da180e269fde785c are reverted later, so the final pull request doesn't contain the functionality (close/open image/tenor-div depending of data existing).

**Comment by GVogeler** [comment]
Seems that the preview of my-charter has lost the previous/next buttons by accident. Can we fix this by reusing the new single-charter-view for my-charter as well?

**Comment by digsc** [comment]
issue concerning my-charter is provisorily fixed. a more sustainable solution comprises reconsideration of inheritance model - see issue icaruseu/mom-ca#202. 
but i think we can merge now?

**Comment by GVogeler** [comment]
It seems that unfortunately saved-charter.widget.xml has the same inheritance problem.

**Comment by digsc** [comment]
surprise surprise...

Von meinem Sony Xperia™-Smartphone gesendet

GVogeler <notifications@github.com> schrieb:



It seems that unfortunately saved-charter.widget.xml has the same inheritance problem.

**Comment by digsc** [comment]
problem with saved-charters is fixed

**Pull request merged**
