### PR TITLE
Seals

### PR DESCRIPTION
**Pull request by StephanMa**
PR for #1061 
Will be tested

### CODE REVIEW

**Comment by NTsch** [comment]
Solves #1061, #563 and #1001.

**Comment by StephanMa** [comment]
Tested with Charter `mom/AT-StiAWilten/Urkunden/001_B/charter`
resulted in...

image

#1061 is fixed but #1001 unfortunately not

**Comment by StephanMa** [comment]
Result of #1061 test

image

lgtm

**Comment by StephanMa** [comment]
@NTsch would you please have a look?

**Comment by yngwi** [comment]
> Result of #1061 test
> 
> image
> 
> lgtm, but...
> 
> It looks kind of odd having a bulletpoint for material and not for seal

I agree, the styling is inconsistent, would it be possible to get rid of the bullet points for all examples as it doesn't make sense if the seal doesn't have one and the other things (material, dimensions) do?

**Comment by NTsch** [comment]
Interestingly, the bullet point from the `<li>` shows up for me in Chrome, but not in Firefox, that's why I missed it. Yes, it should be list elements either everywhere or nowhere, I'll have another look.
For cases like `mom/AT-StiAWilten/Urkunden/001_B/charter`, I could remove the "Siegel" text if it contains no text, like so:
Screenshot from 2022-05-12 14-20-34
I'll do some tests with this.

**Comment by NTsch** [comment]
I've made a few changes, could you look at it again @StephanMa?

**Comment by StephanMa** [comment]
@NTsch LGTM

**Comment by StephanMa** [comment]
closes #563, #1001, #1061

**Pull request merged**
